# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

sudo: required

language: r

cache: packages

cran: https://cran.rstudio.com/

matrix:
  include:

  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        packages:
          - libgdal1-dev
          - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        packages:
          - libgdal1-dev
          - libproj-dev
    before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start

  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        packages:
          - libgdal1-dev
          - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

  - os: osx
    osx_image: xcode8
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_script:
    - Rscript -e "install.packages('rgdal', type = 'source')"

r_build_args: " "

r_check_args: "--as-cran"

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
