sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    r_packages:
    - rgdal
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@DBI", dependencies = FALSE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/SpaDES.core@DBI", dependencies = FALSE)'
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@DBI", dependencies = FALSE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/SpaDES.core@DBI", dependencies = FALSE)'
    r_packages:
    - rgdal
    r_github_packages:
      - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(package_coverage(type = "all", quiet = FALSE)))'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@DBI", dependencies = FALSE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/SpaDES.core@DBI", dependencies = FALSE)'
    r_packages:
    - rgdal
  - os: osx
    osx_image: xcode9.4
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_install:
      - Rscript -e 'install.packages("rgdal", type = "source")'
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@DBI", dependencies = FALSE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/SpaDES.core@DBI", dependencies = FALSE)'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
